all: zad0 zad01 zad1 zad2

test: all

.PHONY: all clean

zad0: zad0.c
	gcc zad0.c -o zad0 

zad1: zad1.c 
	gcc zad1.c -o zad1

zad2: zad2.c 
	gcc zad2.c -o zad2

zad01: zad01.c 
	gcc zad01.c -o zad01

clean:
	find . -type f -executable -delete
