all: zad1 zad2_io zad2_calc

zad1: zad1.c
	gcc zad1.c -o zad1

zad2_io: zad2_io.c 
	gcc zad2_io.c -o zad2_io

zad2_calc: zad2_calc.c 
	gcc zad2_calc.c -o zad2_calc

clean:
	find . -type f -executable -delete
